[package]
name = "rust-design-clock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.4.8"
chrono = "0.4.19"
lazy_static = "1.4.0"
glib = "0.15.12"
libadwaita = "*"